# Local development (H2)
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:planetmeldb;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.database-platform=${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# Server port
server.port=${PORT:8080}
